library:
  log:
    format: text
    level: 5
    caller: false
custom:
  adminServer:
    common:
      hostName: ""
      port: 3332
    basePath: /admintest
    readTimeout: 1s
    writeTimeout: 3s
genCode:
  upstream:
    contextTimeout: 120s
    http:
      basePath: /
      readTimeout: 120s
      writeTimeout: 120s
      common:
        hostName: ""
        port: 8080
  downstream:
    contextTimeout: 120s
    flickr:
      serviceURL: http://localhost:6060
      clientTimeout: 59s
      clientTransport:
        clientTLS:
          insecureSkipVerify: true
    petstore:
      serviceURL: http://localhost:6061
      clientTimeout: 59s
      clientTransport:
        clientTLS:
          insecureSkipVerify: true
