openapi: 3.0.0
info:
  title: Petdemo
  version: 0.0.1
  description: Pet service to demo the sysl codegen capabilties.
  contact:
    name: Sumit Narayan
    email: sumit.narayan@anz.com

paths:
  /random-pet-pic:
    get:
      description: Get a random pet pic from the petstore
      operationId: getRandomPetPic
      security:
        - api_key: []
      responses:
        "200":
          description: Successfully retrieves a random pet image
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PetResponse"
        "400":
          description: No pet found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericError"
        "401":
          description: Unauthorized error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericError"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericError"

components:
  schemas:
    PetResponse:
      type: object
      properties:
        name:
          type: string
        uri:
          type: string
      required:
        - name
        - uri

    GenericError:
      type: object
      properties:
        status:
          $ref: "#/components/schemas/GenericErrorStatus"
      required:
        - status

    GenericErrorStatus:
      type: object
      properties:
        code:
          description: Unique code to differentiate errors as required
          type: string
        description:
          description: Human-readable description of the error
          type: string
      required:
        - code
        - description

  securitySchemes:
    api_key:
      type: apiKey
      name: api_key
      in: header
